### ISSUE TITLE
示例那个bot挂了？

### ISSUE THREAD

**Issue by laoyur** [xuqingfeng/BondReminderBot#1]
加了后，发送指令没吊用

**Comment by xuqingfeng** [comment]
@laoyur 那个 bot 已经停掉了..
(如果你只是需要查看申购、上市信息，可以考虑订阅https://calendar.google.com/calendar/ical/4p7a2319ptcelqhj5b2tn6r1vo%40group.calendar.google.com/public/basic.ics 自动更新)
