### ISSUE TITLE
你好！我下载您的docker-compose文件。出错了，抄作业不会解决问题，麻烦您帮看看

### ISSUE THREAD

**Issue by wlhwlh0482** [xuqingfeng/BondReminderBot#4]
____    __,
  / __/___/ /  ___,
 / _// __/ _ \/ _ \,
/___/\__/_//_/\___/ v4.9.0,
High performance, minimalist Go web framework,
https://echo.labstack.com,
____________________________________O/_______,
                                    O\,
⇨ http server started on [::]:8000,
2023/01/18 03:58:32 W! fail to get update_id,
2023/01/18 03:58:32 W! fail to convert update_id to int,
2023/01/18 03:59:23 getUpdates resp: {"ok":true,"result":[]},
2023/01/18 03:59:23 getUpdates req : map[offset:[1] timeout:[60]],
2023/01/18 03:59:23 getUpdates resp: [],
2023/01/18 04:00:13 getUpdates resp: {"ok":true,"result":[]},
2023/01/18 04:00:13 getUpdates req : map[offset:[1] timeout:[60]],
2023/01/18 04:00:13 getUpdates resp: [],
2023/01/18 04:01:03 getUpdates resp: {"ok":true,"result":[]},
2023/01/18 04:01:03 getUpdates req : map[offset:[1] timeout:[60]],
2023/01/18 04:01:03 getUpdates resp: [],
2023/01/18 04:01:53 getUpdates resp: {"ok":true,"result":[]},
2023/01/18 04:01:53 getUpdates req : map[offset:[1] timeout:[60]],
2023/01/18 04:01:53 getUpdates resp: [],
2023/01/18 04:02:44 getUpdates resp: {"ok":true,"result":[]},
2023/01/18 04:02:44 getUpdates req : map[offset:[1] timeout:[60]],

    
1:C 18 Jan 2023 03:58:31.477 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

1:C 18 Jan 2023 03:58:31.477 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started

1:C 18 Jan 2023 03:58:31.477 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf

1:M 18 Jan 2023 03:58:31.478 * monotonic clock: POSIX clock_gettime

1:M 18 Jan 2023 03:58:31.479 * Running mode=standalone, port=6379.

1:M 18 Jan 2023 03:58:31.479 # Server initialized

1:M 18 Jan 2023 03:58:31.479 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

1:M 18 Jan 2023 03:58:31.479 * Ready to accept connections

**Comment by xuqingfeng** [comment]
这个 issue 我先关了，有问题你再留言。
